import { Product } from "./types";

export interface Specification {
  label: string;
  value: string;
}

const applyMarkup = (price: number) => Math.round(price * 1.15);

export const PRODUCTS: Product[] = [
  {
    id: "sparta-h6-6k",
    name: "Sparta IP66 H6.6K Energy System",
    slug: "sparta-ip66-h6-6k",
    brand_id: null,
    category_id: null,
    description: "Born to Endure. Evolved to Protect. A high-performance all-in-one energy storage solution for residential and small business use.",
    base_price: 217400,
    markup_price: applyMarkup(217400),
    main_image: "/assets/products/sparta.jpg",
    gallery_images: [],
    features: ["IP66 Rated Protection", "Integrated Modular Design", "Smart EMS Control"],
    is_active: true,
    stock_quantity: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    // Added for brand-neutrality/transition
    brand_name: "itel Energy",
    category_name: "Inverters",
    specifications: [
      { label: "Rated Power", value: "6.6kW" },
      { label: "IP Rating", value: "IP66" },
      { label: "Battery Chemistry", value: "LiFePO4" },
      { label: "Warranty", value: "5 Years" },
    ],
  } as any,
  {
    id: "power-go-aio",
    name: "Power Go Portable Power Station",
    slug: "power-go-portable-power-station",
    brand_id: null,
    category_id: null,
    description: "Compact and reliable all-in-one portable power solution. Perfect for camping, mobile office, or home backup during short outages.",
    base_price: 85000,
    markup_price: applyMarkup(85000),
    main_image: "/assets/products/power-go.jpg",
    gallery_images: [],
    features: ["AIO Design", "Rapid Charging", "Lightweight & Compact"],
    is_active: true,
    stock_quantity: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    brand_name: "itel Energy",
    category_name: "Portable Power Stations",
    specifications: [
      { label: "Capacity", value: "500Wh" },
      { label: "Outlets", value: "2x AC, 3x USB, 1x Type-C" },
      { label: "Weight", value: "5.5kg" },
    ],
  } as any,
  {
    id: "power-tank-backup",
    name: "Power Tank Essential Backup",
    slug: "power-tank-essential-backup",
    brand_id: null,
    category_id: null,
    description: "Essential backup power for home devices. High capacity with multiple output ports for reliable energy storage.",
    base_price: 125000,
    markup_price: applyMarkup(125000),
    main_image: "/assets/products/power-tank.jpg",
    gallery_images: [],
    features: ["High Capacity Cells", "Intelligent BMS", "Emergency LED Lighting"],
    is_active: true,
    stock_quantity: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    brand_name: "itel Energy",
    category_name: "Batteries & Energy Storage",
    specifications: [
      { label: "Capacity", value: "1200Wh" },
      { label: "Cycle Life", value: "3000+ Cycles" },
      { label: "Max Discharge", value: "100A" },
    ],
  } as any,
  {
    id: "solar-panel-p6",
    name: "High-Efficiency Solar Panel Star P6",
    slug: "high-efficiency-solar-panel-star-p6",
    brand_id: null,
    category_id: null,
    description: "Premium PV modules designed for higher performance and long-term durability. Includes integrated PID recovery technology.",
    base_price: 48000,
    markup_price: applyMarkup(48000),
    main_image: "/assets/products/star-p6.jpg",
    gallery_images: [],
    features: ["PID Recovery Technology", "Anti-Reflective Coating", "High Efficiency Cells"],
    is_active: true,
    stock_quantity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    brand_name: "itel Energy",
    category_name: "Solar Panels & Kits",
    specifications: [
      { label: "Max Power", value: "450W" },
      { label: "Efficiency", value: "20.5%" },
      { label: "Cell Type", value: "Monocrystalline" },
    ],
  } as any,
  {
    id: "aio-plus-storage",
    name: "Residential Energy Storage AIO Plus",
    slug: "residential-energy-storage-aio-plus",
    brand_id: null,
    category_id: null,
    description: "Advanced one-stop energy storage solution. Integrated design for seamless grid-on and grid-off performance.",
    base_price: 850000,
    markup_price: applyMarkup(850000),
    main_image: "/assets/products/aio-plus.jpg",
    gallery_images: [],
    features: ["Scalable Modular Design", "EMS Driven Connection", "AI Optimized Cycle Life"],
    is_active: true,
    stock_quantity: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    brand_name: "itel Energy",
    category_name: "All-in-One Systems",
    specifications: [
      { label: "System Voltage", value: "48V" },
      { label: "Inverter Type", value: "Hybrid" },
      { label: "Scalability", value: "Up to 15 Units" },
    ],
  } as any,
  {
    id: "lifepo4-pack-5k",
    name: "Safety-First LiFePO4 Battery Pack",
    slug: "safety-first-lifepo4-battery-pack",
    brand_id: null,
    category_id: null,
    description: "Superior battery chemistry ensuring safety and long lifespan. High efficiency and high power density for demanding applications.",
    base_price: 550000,
    markup_price: applyMarkup(550000),
    main_image: "/assets/products/lithium-pack.jpg",
    gallery_images: [],
    features: ["Multi-layer Safety Protection", "Intelligent BMS", "Wide Temperature Range"],
    is_active: true,
    stock_quantity: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    brand_name: "itel Energy",
    category_name: "Batteries & Energy Storage",
    specifications: [
      { label: "Nominal Capacity", value: "5.12kWh" },
      { label: "BMS", value: "Integrated Smart BMS" },
      { label: "Temperature", value: "-20°C to 60°C" },
    ],
  } as any,
];

export const CATEGORIES = [
  { name: "Inverters", tagline: "Reliable power conversion", icon: "Zap" },
  { name: "Batteries & Energy Storage", tagline: "Safe & long-lasting backup", icon: "Battery" },
  { name: "All-in-One Systems", tagline: "Complete integrated power", icon: "Box" },
  { name: "Portable Power Stations", tagline: "Power for life on the go", icon: "Plug" },
  { name: "Solar Panels & Kits", tagline: "Harness clean solar energy", icon: "Sun" },
  { name: "Accessories & Components", tagline: "Essential system parts", icon: "Settings" },
];

export const formatNaira = (amount: number) => {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};
